// <auto-generated />
namespace SCHOOL_MANAGEMENT_SYSTEM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddEmployee_Parent_Education_Salary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEmployee_Parent_Education_Salary));
        
        string IMigrationMetadata.Id
        {
            get { return "202012081614122_AddEmployee_Parent_Education_Salary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
